import Head from 'next/head'
import Image from 'next/image'
import { useState, useContext } from 'react'
import { MainContext } from '../context'
import BigNumber from 'bignumber.js'

export default function Home() {
  const [selectedFile, setSelectedFile] = useState();
  const [img, setImg] = useState();
  const [URI, setURI] = useState();
  const [amount, setAmount] = useState();

  const {
    initialize, getBalance, balance, bundlrInst
  } = useContext(MainContext);

  const uploadImage = async () => {
    try {
      let txn = await bundlrInst.uploader.upload(selectedFile, [{ name: "Content-Type", value: "image/png" }]);
      setURI(`http://arweave.net/${txn.data.id}`);
    }
    catch (error) {
      console.log('error with upload: ', error);
    }
    getBalance();
  }

  const handleFileChange = (e) => {
    const reader = new FileReader();

    const file = e.target.files[0];
    if (file) {
      reader.onloadend = () => {
        if (reader.result) {
          setSelectedFile(Buffer.from(reader.result));
        }
      };
      reader.readAsArrayBuffer(file);
      const objectUrl = URL.createObjectURL(file);
      setImg(objectUrl);
    }
  }

  const fundWallet = async () => {
    if (!amount) return;
    const parseAmount = parseInput(amount);
    try {
      let response = await bundlrInst.fund(parseAmount);
      console.log('wallet funded: ', response);
    }
    catch (error) {
      console.log('error funding wallet: ', error);
    }
    getBalance();
  }

  const parseInput = (input) => {
    const conversion = new BigNumber(input).multipliedBy(bundlrInst.currencyConfig.base[1]);
    if (conversion.isLessThan(1)) {
      console.log('error: value too small');
      return;
    } else {
      return conversion;
    }
  }

  return (
    <div>
      <Head>
        <title>Arweave/Bundlr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {!balance && <button onClick={initialize}>Initialize</button>}
        {balance && (
          <>
            <p>balance: {balance}</p>
            <input placeholder='add funds'
              onChange={(e) => setAmount(e.target.value)} />
            <button onClick={fundWallet}>fund</button>
          </>
        )
        }
        <div style={{ paddingTop: '10em' }}>
          <input
            type='file'
            onChange={handleFileChange}
          />
          <button style={button} onClick={uploadImage}>
            Upload Image
            </button>
        </div>
        {img &&
          <div style={previewFlex}>
            <div style={{ margin: '0 auto' }}>
              <h3>Our Image</h3>
              {img && (
                <div>
                  <Image src={img} width={128} height={128} alt="local preview" style={previewStyle} />
                </div>
              )
              }
            </div>
            <div style={{ margin: '0 auto' }}>
              <h3>Arweave Image</h3>
              {URI && (
                <>
                  <Image src={URI} width={128} height={128} alt="arweave preview" style={previewStyle} />
                  <a href={URI} target="_blank" rel="noreferrer">{URI}</a>
                </>
              )
              }
            </div>
          </div>}
      </main>
    </div>
  )
}
const previewStyle = {
  margin: '0 auto'
}

const previewFlex = {
  display: 'flex',
}

const button = {
  outline: 'none',
  border: '1px solid black',
  backgroundColor: 'white',
  padding: '10px',
  width: '200px',
  marginBottom: 10,
  cursor: 'pointer',
}
